server:
  port: 8080

db:
  postgres:
    test:
      driver: "postgres"
      host: "localhost"
      port: 5432
      user: $USER
    prod:
      driver: "postgres"
      host: "localhost"
      port: 5432
      user: "postgres"